# Generated by Django 5.0.6 on 2024-05-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=253)),
                ('fullname', models.CharField(max_length=100)),
            ],
        ),
    ]
