# Generated by Django 5.0.6 on 2024-05-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menudecompra', '0005_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, default='static/img/product_images/default.jpg', null=True, upload_to='static/img/product_images/'),
        ),
    ]
