# Generated by Django 5.0.6 on 2024-05-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menudecompra', '0007_alter_product_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo_url',
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, default='img/product_images/default.jpg', null=True, upload_to='product_images/'),
        ),
    ]
