# Generated by Django 5.0.6 on 2024-05-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menudecompra', '0008_remove_product_photo_url_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, default='product_images/default.jpg', null=True, upload_to='product_images/'),
        ),
    ]
