# Generated by Django 5.0.6 on 2024-05-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menudecompra', '0009_alter_product_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image_url',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='product_images/default.jpg', null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, default='product_images/cangreburguer.jpg', null=True, upload_to='product_images/'),
        ),
    ]
